Cash-craftar: Making the Project
mahdinoori2000/cash-crafter pull request #1
Opened 2024-01-22 08:32 UTC by mahdinoori2000

### What is added

- **Splash screen:** A simple page with the name of  app, and links to the sign up and log in pages.
- Sign up and log in pages
-  The user can register in the app with full name, email and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in.

- [ ] - Home page (categories page)
- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- [ ] Transactions page
- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new category" page

- Use Postgres as your database.
- Use devise for authentication.
- Validate all user input to make sure that anyone with bad intentions cannot compromise your app.
- The project is deployed and accessible online.

2024-01-26 12:00 UTC, fobadara requested changes
Hi @mahdinoori2000, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![REDO](https://user-images.githubusercontent.com/62938735/260208741-25cd532c-dea0-4827-bb4f-5412e8493916.gif)

## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code
✅ Good first attempt
✅ Good implementation of the principle of separating concerns.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-26 12:00 UTC, fobadara commented on README.md
> +<a href='https://drive.google.com/file/d/1tvt-dI-l5dmDdsR-owEwPreH-wXSWU7u/view?usp=sharing'>Video presentation</a>
[REQUIRED] Kindly ensure that your video contains a highlight about a piece of the code you find interesting or are proud of making.

2024-01-26 12:00 UTC, fobadara commented on app/views/devise/registrations/new.html.erb
[REQUIRED] Kindly ensure that your design matches Gregoire's design in terms of composition and layout. Please implement the changes requested in the image below

Template
![image](https://github.com/mahdinoori2000/cash-crafter/assets/62938735/ed60cac9-0a3f-4c16-936f-5cb5055e1ae2)

Your Design
![image](https://github.com/mahdinoori2000/cash-crafter/assets/62938735/4ec6a78d-8227-46ed-ae21-87d4db73fcd7)

2024-01-26 12:00 UTC, fobadara commented on app/views/users/splash.html.erb
> +<h1 class="title">Cash Crafter</h1>
[REQUIRED] Kindly use black for the font color of your app name just like in the template
![image](https://github.com/mahdinoori2000/cash-crafter/assets/62938735/462f303d-2653-4a14-88d7-56539c76ac5d)

2024-01-26 12:00 UTC, fobadara commented on app/views/devise/sessions/new.html.erb
[REQUIRED] Please make sure that your design is similar to the template in terms of colour, layout and typography. Please look over the design and take note of the suggestions in the image below.

![image](https://github.com/mahdinoori2000/cash-crafter/assets/62938735/f11d9d76-66a4-41e0-9686-a1e858066da0)

2024-01-26 12:00 UTC, fobadara commented on app/views/categories/index.html.erb
[REQUIRED] Kindly ensure that your design matches the template. Kindly implement the suggestions in the image below while making sure they are close to the template

![image](https://github.com/mahdinoori2000/cash-crafter/assets/62938735/f8895921-213c-44bd-8853-e40248e6c9f2)

Template
![image](https://github.com/mahdinoori2000/cash-crafter/assets/62938735/c4ab4fa9-0b9f-4146-82ae-8fbbe987f7d6)

2024-01-26 12:00 UTC, fobadara commented on app/views/payments/new.html.erb
[REQUIRED] When I click the back button on the transaction creation I am taken to this page `https://cash-crafter.onrender.com/payments` which shows the error in the image below. Kindly fix this to make your project look more professional.

<img width="1440" alt="image" src="https://github.com/mahdinoori2000/cash-crafter/assets/62938735/075ffbab-068c-4713-9b41-405c5d712349">

2024-01-26 12:00 UTC, fobadara commented on app/views/payments/new.html.erb
[OPTIONAL] Your form doesn't get submitted if any of the inputs are empty but it is a good UX if it displays an error message guiding the users to fill in the necessary data

2024-01-26 12:00 UTC, fobadara commented on app/controllers/users_controller.rb
> +  def splash; end
[REQUIRED] Kindly remove this since it is not in use in order to make your project more professional

2024-01-26 12:00 UTC, fobadara commented on app/controllers/users_controller.rb
> +  def edit; end
[REQUIRED] Kindly remove this since it is not in use in order to make your project more professional

2024-01-26 12:00 UTC, fobadara commented on app/controllers/users_controller.rb
> +  def show; end
[REQUIRED] Kindly remove this since it is not in use in order to make your project more professional

2024-01-26 12:00 UTC, fobadara commented on app/controllers/payments_controller.rb
> +  def show; end
[REQUIRED] Kindly remove this since it is not in use in order to make your project more professional

2024-01-26 12:00 UTC, fobadara commented on config/routes.rb
> +  resources :users
[REQUIRED] I noticed that you are using resources without `only` or `except` and this creates routes for actions that you are not using in your controllers like the `show` action in your users and categories controllers. Kindly ensure that resources only create routes that you have actions for in your controller with `only` or `except`.

2024-01-26 12:00 UTC, fobadara commented on config/routes.rb
> +  post '/categories/:category_id/payment' => 'payments#create', as: :create_payment
[REQUIRED] The endpoints you have here have already been created by the resources command in line 9 of this routes file. Either use `only` or `except` to exclude these routes from being created by resources if you want to keep the names you are adding with `as:` or remove these lines and stick to using resources with the names that are automatically generated for you

2024-01-27 10:16 UTC, prolajumokeoni approved these changes
Hi @mahdinoori2000 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Changes requested have been implemented and app works properly  ✅ 
   

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-27 13:03 UTC, merged